---
title: 'DL for Epidemiologists: Dataset'
author: "Stylianos Serghiou"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output:
  prettydoc::html_pretty:
    # no code_folding available
    theme: hpstr      # or: architect; https://github.com/yixuan/prettydoc
    highlight: github # or: vignette
    toc: TRUE         # no toc_float available
    df_print: kable   # obviates %>% kable; does not replace styling though
  tufte::tufte_handout: default
  pdf_document:
    highlight: tango
    df_print: kable
    latex_engine: pdflatex
    keep_tex: yes
  rmdformats::readthedown:
    highlight: kate
    df_print: kable    # obviates %>% kable; does not replace styling though
    code_folding: hide # or: show; (comment out to not give option)
  tufte::tufte_html: 
    toc: TRUE
  epuRate::epurate:
    df_print: kable
    toc: yes
  html_document:
    highlight: tango
    theme: sandstone
    df_print: kable
    toc: yes
    toc_depth: 2
    toc_float: yes
    css: "path_to_custom.css"
header-includes:
- \DeclareUnicodeCharacter{3B8}{~}
- \DeclareUnicodeCharacter{3B1}{~}
- \DeclareUnicodeCharacter{3B2}{~}
- \DeclareUnicodeCharacter{223C}{~}
- \DeclareUnicodeCharacter{2264}{~}
- \DeclareUnicodeCharacter{2265}{~}
- \DeclareUnicodeCharacter{2581}{~}
- \DeclareUnicodeCharacter{2582}{~}
- \DeclareUnicodeCharacter{2583}{~}
- \DeclareUnicodeCharacter{2585}{~}
- \DeclareUnicodeCharacter{2586}{~}
- \DeclareUnicodeCharacter{2587}{~} 
- \DeclareUnicodeCharacter{FB00}{~} 
- \usepackage{graphicx}
editor_options: 
  chunk_output_type: inline
---

<style>
p {

text-align: justify;
text-justify: interword;
padding: 0 0 0.5em 0

}
</style>

```{r setup, include=FALSE}
# Load packages
library(knitr)
library(rmdformats)
library(kableExtra)
library(ggplot2)
library(magrittr)



######### knitr

# Define chunk options
opts_chunk$set(
  echo = T,
  cache = F,  # if TRUE, no need to rerun chunks
  # cache.lazy = TRUE,  # use with big objects (>1 GB)
  cache.comments = F,  # do not rebuild if comments change
  tidy = F,  # can play with this
  warning = F, 
  message = F,
  comment = NA,
  fig.align = "center",
  fig.width = 7,
  # fig.path = "Figs/",  # export all figures to dir Figs
  linewidth = 91,
  width = 75
)


# Initiatialize hook
hook_output = knit_hooks$get("output")


# Hook to wrap output text when it exceeds 'n' using linewidth
knit_hooks$set(output = function(x, options) {
  
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    
    # wrap lines wider than 'n' 
    if (any(nchar(x) > n)) 
      x <- strwrap(x, width = n)
      x <- paste(x, collapse = "\n")
  }
  hook_output(x, options)
})


# Times a chunk and prints the time it took to run it under the chunk
# To time a chunk, include in the chunk options: {r my_chunk, timeit=TRUE}
knitr::knit_hooks$set(timeit = local({
  now = NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res = difftime(Sys.time(), now)
      now <<- NULL
      # use options$label if you want the chunk label as well
      paste('Time for this code chunk:', as.character(res))
    }
  }})
)


# For more knitr options visit: https://yihui.name/knitr/options/
# and his github page: https://github.com/yihui/knitr-examples



######### kableExtra

options(knitr.kable.NA = ''  # replace NAs in tables with blank
        , digits = 3)          # round digits (doesn't work without this here!)

## Example use
# data.frame(x = c(1,2,3), y = c(4,5,6), z = c(7,8,9)) %>% 
#   kable(booktabs = T) %>% kable_styling()

# Function to simplify table styling
sable <- function(tab, escape = T, full_width = F, drop = F, font_size = 12) {
  if (drop) {
    tab %>%
      kable(escape = escape, booktabs = T) %>%
      collapse_rows(valign = "top") %>% 
      kable_styling("striped", 
                    position = "center", 
                    full_width = full_width, 
                    font_size = font_size)
  } else {
    tab %>%
      kable(escape = escape, booktabs = T) %>%
      kable_styling("striped", 
                    position = "center", 
                    full_width = full_width,
                    font_size = font_size)
  }
}

## Guidelines
# No longer need to define options(knitr.table.format = "html"). It is now automatically done as soon as you load kableExtra
# No need to run kable() every time - done automatically as soon as you load kableExtra
# Loading kableExtra nullifies any styling applied by df_table: kable in the preamble - if you are content with standard formatting, DO NOT load kableExtra



#########  ggplot2

# Set up preferred theme in ggplot2
my_theme <- 
  # this and theme_minimal() are my favorite
  theme_light() +  
  theme(
    axis.ticks = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.text.x = element_text(margin = margin(t = 3)),
    axis.text.y  = element_text(margin = margin(r = 3)),
    legend.key = element_rect(colour = NA, fill = NA),  # Avoid borders
    panel.border = element_blank(),
    text = element_text(color = "grey20"),
    title = element_text(face = "bold")
  )

# Make the above theme the default theme
original_theme <- theme_set(my_theme)

# Use ggsave to save plots after plotting - this reduces size dramatically



######### Live preview

# Preview the HTML without having to re-knit
# https://www.r-bloggers.com/create-r-markdown-reports-and-presentations-even-better-with-these-3-practical-tips/amp/

# xaringan::infinite_moon_reader()




######### Tabbed sections

# You can organize content using tabs by applying the .tabset class attribute to headers within a document. This will cause all sub-headers of the header with the .tabset attribute to appear within tabs rather than as standalone sections. For example:

## Quarterly Results {.tabset}

### By Product



######### Update package

# To update the package use:
# Replace ~/serghiouTemplates/inst/rmarkdown/templates/report/skeleton.rmd
# library(devtools); setwd("/Users/Stelios/"); install("serghiouTemplates")
```


# Setup {.tabset}

## Load libraries

```{r setup_2}
# Load packages
library(cowplot)
library(tidyverse)

# Source code
source("figure-2_dataset.R")
```


## Define functions

```{r}
plot_data <- function(df = df_plot, type = data_type) {
  
  df %>%
    filter(id == type) %>% 
    ggplot(aes(x = x, y = y, color = labels, shape = labels)) +
    geom_point(show.legend = F) +
    ggtitle(type) +
    theme_bw() +
    theme(
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title = element_blank(),
      panel.border = element_blank(),
      panel.grid = element_blank(),
      panel.spacing = unit(2, "lines"),
      plot.title = element_text(hjust = 0.5, vjust = 3),
      strip.background = element_blank(),
      # strip.text.x = element_blank(),
      text = element_text(
        color = "grey20",
        face = "bold",
        family = "Helvetica",
        size = 12
      ),
    )
}
```


***


# Create datasets

The code for creating the data was taken from the GitHub of TensorFlow Playground [here](https://github.com/tensorflow/playground/blob/master/src/dataset.ts) and is licensed under Apache 2.0.


```{r}
# Define seed
set.seed(2253)

# Define parameters (noise has to be between 0 and 0.5)
noise <- 0.1
numSamples <- 200

# Create data
playground <- list(
  XOR = classifyXORData(numSamples, noise),
  Spiral = classifySpiralData(numSamples, noise),
  Circle = classifyCircleData(numSamples, noise),
  Gaussian = classifyTwoGaussData(numSamples, noise)
)

# Data for plotting
df_plot <- playground %>% 
  map_dfr(as_tibble) %>% 
  setNames(c("x", "y", "labels")) %>%
  mutate(
    id = rep(names(playground), each = numSamples),
    labels = factor(labels)
  )
```


***


# Plot

## Plot without labels

```{r}
# Plot
df_plot %>% 
  ggplot(aes(x = x, y = y, color = labels, shape = labels)) +
  geom_point(show.legend = F) +
  facet_wrap(~ id, ) +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    panel.border = element_blank(),
    panel.grid = element_blank(),
    panel.spacing = unit(2, "lines"),
    strip.background = element_blank(),
    # strip.text.x = element_blank(),
    text = element_text(
      color = "grey20",
      face = "bold",
      family = "Helvetica",
      size = 12
    ),
  )

# Save
ggsave("../images/figure_2_non-linear-data.pdf", width = 6, height = 4)
```


## Plot with labels

Plot panels.

```{r}
p <- purrr::map(names(playground), ~ plot_data(df_plot, .))
```


Create unified figure.

```{r}
# Plot
cowplot::plot_grid(
  p[[1]], p[[2]], p[[3]], p[[4]],
  labels = c("A)", "B)", "C)", "D)"),
  ncol = 2,
  nrow = 2,
  label_fontcolour = "grey20",
  label_fontfamily = "Helvetica",
  label_fontface = "bold",
  label_size = 14,
  vjust = 1.5,
  scale = 0.75
)

# Save
ggsave("../images/figure_2_non-linear-data_panels.pdf", width = 6, height = 5)
```


***


# Documentation {.tabset}

## Session Info

```{r session_info, echo=FALSE}
print(sessionInfo(), locale = F)
```


## References

```{r refs, echo=FALSE}
(.packages()) %>% sort %>% lapply(citation) %>% lapply(c) %>% unique
```
